public with sharing class SkyTest24
                        {
                            public SkyTest24()
                            {
                                        
                                //sdfsfse//sfe//sdfsfse//sfe
                            }
                            
                            public void myMethod()
                            {
                                Integer ra=9;
                                Integer r2=10;
                            }
                            
                        }